title: "Zachary Geelalsingh's Personal Website"
description: "A personal website where I showcase my projects and blog about my experiences."
author: "Zachary Geelalsingh"
email: "zgeelalsingh2022@my.fit.com"
theme: minima
url: "https://zacgee.github.io"
